import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { GraphQLClient , gql } from 'graphql-request'
import BlogCard  from '../../components/BlogCard'

const graphcms = new GraphQLClient("https://api-us-west-2.hygraph.com/v2/clfp7z09m0wx401t9998xduvp/master");

const QUERY = gql`

  {
    posts{
      id,
      title,
      dataPublished,
      slug,
      content {
        html
      }
      author {
        name,
        avatar{
          url
        }
      }
      coverPhoto{
          url
      }
    }  
  }

`;

export async function getStaticProps(){
  const { posts } = await graphcms.request(QUERY);
  return {

    props: {
      posts,
    },

    revalidate : 10,

  };
}

export default function Home({posts}) {
  return (
    <div className={styles.grid}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}> 

        {
            posts.map((post)=>(
                <BlogCard
                  title = {post.title}
                  author = {post.author}
                  coverPhoto = {post.coverPhoto}
                  key ={post.id}
                  dataPublished = {post.dataPublished}
                  slug = {post.slug}
                />
            ))          

        }
      </main>
    </div>
  );
}
